apiVersion: skaffold/v2beta29
kind: Config
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: rminz/skaffold-test
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.GIT_REV}}"
  local:
    push: false
    concurrency: 2
deploy:
  helm:
    releases:
      - name: "{{.ENVIRONMENT}}"
        setValueTemplates:
          Environment: "{{.ENVIRONMENT}}"
          image.tag: "{{.GIT_REV}}"
        chartPath: ci/charts/web
        valuesFiles:
          - ci/deployment-values/common.yaml
          - ci/deployment-values/{{.ENVIRONMENT}}.yaml
profiles:
  - name: CI
    activation:
      - env: CI=true
    patches:
      - op: replace
        path: /build/local/push
        value: true