---
apiVersion: skaffold/v2beta29
kind: Config
portForward:
  - resourceType: deployment
    resourceName: dev-web
    namespace: default
    port: 80
    localPort: 8080
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: rminz/skaffold-test
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      ignoreChanges: false
  local:
    concurrency: 2
    push: false
test:
  - context: .
    image: rminz/skaffold-test
    custom:
      - command: grype $IMAGE
deploy:
  kubectl:
    manifests:
      - "ci/dev-manifest/*.yaml"