apiVersion: skaffold/v2beta29
kind: Config
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: rminz/skaffold-test
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      ignoreChanges: true
  local:
    concurrency: 2
    push: false
deploy:
  helm:
    releases:
      - name: app
        artifactOverrides:
          image: rminz/skaffold-test
        chartPath: ci/charts/web
        valuesFiles:
          - ci/deployment-values/common.yaml
        imageStrategy:
          helm:
            explicitRegistry: false
profiles:
  - name: stage
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - ci/deployment-values/stage.yaml
  - name: production
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - ci/deployment-values/production.yaml
