---
apiVersion: skaffold/v2beta29
kind: Config
portForward:
  - resourceType: deployment
    resourceName: dev-web
    namespace: default
    port: 80
    localPort: 8080
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: rminz/skaffold-test
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      ignoreChanges: false
  local:
    concurrency: 2
    push: false
profiles:
  - name: production
    activation:
      - env: CI=true
    deploy:
      helm:
        releases:
          - name: production
            artifactOverrides:
              image: rminz/skaffold-test
            chartPath: ci/charts/web
            imageStrategy:
              helm:
                explicitRegistry: false
    patches:
      # Enable push when the the profile is activated
      - op: replace
        path: /build/local/push
        value: true
      - op: replace
        path: /build/tagPolicy/gitCommit/ignoreChanges
        value: true
  - name: dev
    activation:
      - env: ENV=dev
    deploy:
      kubectl:
        manifests:
          - "ci/dev-manifest/*.yaml"