apiVersion: v1
kind: Service
metadata:
  name: dev-web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: dev